---
- hosts: control_plane
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    - name: "K8S  join command"
      add_host:
        name:   "K8S_JOIN"
        join_command:  "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      command: "{{ hostvars['K8S_JOIN']['join_command'] }}"
      register: output
    - name: Demo
      debug: 
        var: output